import { saveAs } from 'file-saver';
export function downloadMarkdown(content: string, filename: string = 'practice-forge-guide.md') {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  saveAs(blob, filename);
}
function mdToHtml(md: string): string {
  return md
    // Code blocks
    .replace(/```(?:[a-z]+)?\n([\s\S]*?)\n```/gim, '<pre><code>$1</code></pre>')
    // Headings
    .replace(/^# (.*$)/gim, '<h1>$1</h1>')
    .replace(/^## (.*$)/gim, '<h2>$1</h2>')
    .replace(/^### (.*$)/gim, '<h3>$1</h3>')
    // Lists
    .replace(/^\* (.*$)/gim, '<ul><li>$1</li></ul>')
    .replace(/^- (.*$)/gim, '<ul><li>$1</li></ul>')
    .replace(/<\/ul>\s*<ul>/g, '')
    // Inline styling
    .replace(/\*\*(.*)\*\*/gim, '<strong>$1</strong>')
    .replace(/\*(.*)\*/gim, '<em>$1</em>')
    .replace(/`(.*?)`/g, '<code>$1</code>')
    // Paragraphs
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br/>');
}
export function downloadHTML(markdownContent: string, filename: string = 'practice-forge-guide.html') {
  const htmlBody = mdToHtml(markdownContent);
  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PracticeForge Guide</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fredericka+the+Great&family=Inter:wght@400;600;700&display=swap" rel="stylesheet">
    <style>
        :root {
            --primary: #F38020;
            --secondary: #764ba2;
            --background: #FDFBF7;
            --text: #1a1a1a;
            --code-bg: #1e1e1e;
        }
        body {
            box-sizing: border-box;
            min-width: 200px;
            max-width: 900px;
            margin: 0 auto;
            padding: 40px;
            background-color: var(--background);
            font-family: 'Inter', sans-serif;
            color: var(--text);
            line-height: 1.6;
        }
        .sketchy-frame {
            border: 3px solid #1a1a1a;
            padding: 3rem;
            border-radius: 2% 98% 2% 98% / 98% 2% 98% 2%;
            background: white;
            box-shadow: 12px 12px 0px 0px #1a1a1a;
        }
        header {
            text-align: center;
            margin-bottom: 3rem;
            border-bottom: 3px double #1a1a1a;
            padding-bottom: 1.5rem;
        }
        h1, h2, h3 {
            font-family: 'Fredericka the Great', cursive;
            color: var(--secondary);
            margin-top: 1.5em;
        }
        h1 { font-size: 2.5rem; color: var(--primary); margin-top: 0; }
        code {
            color: var(--primary);
            background-color: rgba(243, 128, 32, 0.08);
            padding: 0.2em 0.4em;
            border-radius: 4px;
            font-family: monospace;
        }
        pre {
            background: var(--code-bg);
            color: #fff;
            padding: 1.5rem;
            border-radius: 12px;
            overflow-x: auto;
            border: 2px solid #1a1a1a;
            box-shadow: 4px 4px 0px 0px #1a1a1a;
        }
        pre code {
            background: transparent;
            color: inherit;
            padding: 0;
        }
        ul { padding-left: 1.5rem; }
        li { margin-bottom: 0.5rem; }
        footer {
            margin-top: 4rem;
            font-size: 0.85rem;
            text-align: center;
            opacity: 0.5;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        @media (max-width: 767px) {
            body { padding: 20px; }
            .sketchy-frame { padding: 1.5rem; }
        }
    </style>
</head>
<body>
    <div class="sketchy-frame">
        <header>
            <h1>PracticeForge AI</h1>
            <p><em>Forged on ${new Date().toLocaleDateString()}</em></p>
        </header>
        <article>
            ${htmlBody}
        </article>
        <footer>
            Generated by PracticeForge AI • Structured Mastery
        </footer>
    </div>
</body>
</html>
  `;
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  saveAs(blob, filename);
}
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (err) {
    console.error('Failed to copy: ', err);
    return false;
  }
}