import { saveAs } from 'file-saver';
export function downloadMarkdown(content: string, filename: string = 'practice-guide.md') {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  saveAs(blob, filename);
}
export function downloadHTML(markdownContent: string, filename: string = 'practice-guide.html') {
  // Simple conversion of basic MD to HTML for the export file
  // In a real app we might use a library, but for portability we wrap it in a styled container
  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PracticeForge Guide</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fredericka+the+Great&family=Inter:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.2.0/github-markdown.min.css">
    <style>
        :root {
            --primary: #F38020;
            --secondary: #764ba2;
            --background: #FDFBF7;
        }
        body { 
            box-sizing: border-box; 
            min-width: 200px; 
            max-width: 980px; 
            margin: 0 auto; 
            padding: 45px;
            background-color: var(--background);
            font-family: 'Inter', sans-serif;
        }
        .markdown-body {
            background-color: transparent !important;
            font-family: 'Inter', sans-serif;
        }
        .markdown-body h1, .markdown-body h2, .markdown-body h3 {
            font-family: 'Fredericka the Great', cursive;
            color: var(--secondary);
            border-bottom: 2px dashed #eee;
        }
        .markdown-body code {
            color: var(--primary);
            background-color: rgba(243, 128, 32, 0.1);
        }
        @media (max-width: 767px) { body { padding: 15px; } }
        .sketchy-frame {
            border: 3px solid #1a1a1a;
            padding: 2rem;
            border-radius: 2% 98% 2% 98% / 98% 2% 98% 2%;
            background: white;
            box-shadow: 8px 8px 0px 0px #1a1a1a;
        }
    </style>
</head>
<body>
    <div class="sketchy-frame">
        <header style="text-align: center; margin-bottom: 2rem; border-bottom: 2px solid #1a1a1a; padding-bottom: 1rem;">
            <h1 style="font-family: 'Fredericka the Great', cursive; color: var(--primary); margin: 0;">PracticeForge AI</h1>
            <p style="margin: 0.5rem 0 0 0; font-style: italic;">Your custom pedagogical guide</p>
        </header>
        <article class="markdown-body">
            ${markdownContent.replace(/\n/g, '<br/>')} 
            <!-- Note: Simple replace for export purposes; usually handled by a proper MD-to-HTML parser -->
        </article>
        <footer style="margin-top: 3rem; font-size: 0.8rem; text-align: center; opacity: 0.6;">
            Generated by PracticeForge AI • ${new Date().toLocaleDateString()}
        </footer>
    </div>
</body>
</html>
  `;
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  saveAs(blob, filename);
}
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (err) {
    console.error('Failed to copy: ', err);
    return false;
  }
}